### ISSUE TITLE
Unable to resolve using (add-tap #'p/submit) 

### ISSUE THREAD

**Issue by thecontinium** [djblue/portal#58] opened 2021-06-11 09:21 UTC
I am connection to an nrepl on a server with `lein repl :connect 7679`and I get the following exception thrown when ` (add-tap #'p/submit) ` but all works when I use the depreciated `(p/tap)`

``` clojure
user=> (require '[portal.api :as p])
nil
user=> (add-tap #'p/submit)
             java.lang.RuntimeException: Unable to resolve var: p/submit in this context
clojure.lang.Compiler$CompilerException: Syntax error compiling var at (1:1).

user=> (p/tap)
nil
user=>

```
This only happens when I connect to a running nrepl.

Cheers

**Comment by djblue** [comment] 2021-06-11 15:27
Hi @thecontinium, what version of portal are you working with.? `portal.api/submit` was added as part of 0.9.0.

**Comment by thecontinium** [comment] 2021-06-12 08:13
Hi @djblue, I am using the LATEST version. If I `lein repl` rather than `lean repl :connect 12345` it works fine.

**Comment by djblue** [comment] 2021-06-13 00:58
What does the project you are connecting to via `lein repl :connect 12345` look like? I tried [./examples/jvm/](https://github.com/djblue/portal/tree/master/examples/jvm) with latest portal and lein and can't reproduce.

**Comment by thecontinium** [comment] 2021-06-13 08:06
It's connecting to an nrepl server running inside a docker container where ports 12345 and 12346 are mapped to the host machine and started with 

``` clojure
(start-server :bind "0.0.0.0" :port 12345)
```

After connecting this works although I have to paste the portal server url output on startup into chrome manually on the host machine.

``` clojure
(require '[portal.api :as p]) (p/start {:portal.launcher/port 12346})(p/open)(p/tap)
```

using `(add-tap #'p/submit)` instead of `(p/tap)` throws the exception.

The same project just starting a repl on the host with `lein repl` works with 

``` clojure 
(require '[portal.api :as p]) (p/open) (add-tap #'p/submit)
```

**Comment by djblue** [comment] 2021-08-14 04:32
Since I wasn't able to reproduce, closing for now.

**Closed by djblue** 2021-08-14 04:32 UTC
